spring.datasource.url=jdbc:postgresql://localhost:5433/sport_db
spring.datasource.username=postgres
spring.datasource.password=46812

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080